services:
  postgresdb:
    image: postgres
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
      - DB_HOST=postgres
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    volumes:
      - genzineers:/var/lib/postgresql
  app:
    depends_on:
      - postgresdb
    build: ./
    env_file: ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=postgresdb
    develop:
      watch:
      - action: rebuild
        path: .
        target: .
    stdin_open: true
    tty: true

volumes: 
  genzineers:


